### PR TITLE
Swifttype fixes

### LINKED ISSUE #160: Entering a trailing space in site search returns no results
We've noticed that some valid search terms are returning a blank results page. In these cases, we've also noticed a trailing "+" in the URL query string.

For example:

- Results: https://www.baltimorecountymd.gov/search/results.html?q=subscribe

- No results: https://www.baltimorecountymd.gov/search/results.html?q=subscribe+

It appears that whenever a trailing + appears in the query string, no results are returned. This seems to occur whenever a user enters a search term with a space at the end into the search box.

The expected behavior is that the same results are returned regardless of whether a space is included at the end of the search.

### PR DESCRIPTION
**Pull request by martypowell**
Fixes #160 - trailing space issue

### CODE REVIEW

File: js/page-specific/swiftype-search-results.js [hunk 1]
```diff
@@ -8,13 +8,21 @@ baltimoreCounty.pageSpecific.swiftypeSearchResults = (function swiftypeSearchRes
 
 	function getSearchResults(searchTerm, pageNumber) {
 		var currentPageNumber = pageNumber || 1;
-		var cleanedSearchTerm = searchTerm.replace(/\+/g, '%20');
+		var cleanedSearchTerm = searchTerm;
```
Comment (mxsnyder) [inline js/page-specific/swiftype-search-results.js]: Just in case, it might be worth trimming searchTerm. Probably not necessary, but it's a good safeguard.

File: js/page-specific/swiftype-search-results.js [hunk 2]
```diff
@@ -8,13 +8,21 @@ baltimoreCounty.pageSpecific.swiftypeSearchResults = (function swiftypeSearchRes
...
 
-		$.ajax(constants.keywordSearch.urls.api + cleanedSearchTerm + '/' + currentPageNumber).then(searchResultRequestSuccessHandler, searchResultRequestErrorHandler);
+		// Ensure the last character is not '+' as the the trailing space causes no results
+		if (cleanedSearchTerm[cleanedSearchTerm.length - 1] === '+') {
+			cleanedSearchTerm = cleanedSearchTerm.substr(0, (cleanedSearchTerm.length - 1));
```
Comment (mxsnyder) [inline js/page-specific/swiftype-search-results.js]: Unnecessary, but you could also do **cleanedSearchTerm.slice(0, -1)** which is a little more readable.
