### PR TITLE
Bad Search Query Fixes

### LINKED ISSUE #173: Search does not return results when "/" is used in the search term
Example search term spay/neuter. This is actually an autocomplete item.

### PR DESCRIPTION
**Pull request by martypowell**
Fixes #173 

replaces special characters in the search string if they exist.

- \
- /
- \#
- ?
- &

### CODE REVIEW

File: js/page-specific/swiftype-search-results.js [hunk 1]
```diff
@@ -6,19 +6,40 @@ baltimoreCounty.pageSpecific.swiftypeSearchResults = (function swiftypeSearchRes
...
 		if (cleanedSearchTerm[cleanedSearchTerm.length - 1] === '+') {
 			cleanedSearchTerm = cleanedSearchTerm.slice(0, -1);
 		}
 
-		cleanedSearchTerm = cleanedSearchTerm.replace(/\+/g, '%20');
+		var searchTerms = cleanedSearchTerm.split('+');
+		for (var i = 0; i < searchTerms.length; i += 1) {
+			var term = decodeURIComponent(searchTerms[i]);
+			term = term
+				.replace(/\?/g, '')
```
Comment (mxsnyder) [inline js/page-specific/swiftype-search-results.js]: It might be a little cleaner to do the replace in one operation using **/[?#&/\\]/g**.

File: js/page-specific/swiftype-search-results.js [hunk 2]
```diff
@@ -6,19 +6,40 @@ baltimoreCounty.pageSpecific.swiftypeSearchResults = (function swiftypeSearchRes
...
+				.replace(/&/g, 'and')
+				.replace(/\//g, ' ')
+				.replace(/\\/g, ' ');
+
+			var encodedTerm = encodeURIComponent(term);
+			safeSearchTerms.push(encodedTerm);
+		}
+		cleanedSearchTerm = safeSearchTerms.join('+');
+
+		return cleanedSearchTerm.replace(/\+/g, '%20');
```
Comment (mxsnyder) [inline js/page-specific/swiftype-search-results.js]: Should this be done inside your loop now?

File: js/page-specific/swiftype-search-results.js [hunk 3]
```diff
@@ -6,19 +6,40 @@ baltimoreCounty.pageSpecific.swiftypeSearchResults = (function swiftypeSearchRes
...
+		var cleanedSearchTerm = termToClean.trim();
+		var safeSearchTerms = [];
 		// Ensure the last character is not '+' as the the trailing space causes no results
 		if (cleanedSearchTerm[cleanedSearchTerm.length - 1] === '+') {
 			cleanedSearchTerm = cleanedSearchTerm.slice(0, -1);
 		}
 
-		cleanedSearchTerm = cleanedSearchTerm.replace(/\+/g, '%20');
+		var searchTerms = cleanedSearchTerm.split('+');
+		for (var i = 0; i < searchTerms.length; i += 1) {
```
Comment (mxsnyder) [inline js/page-specific/swiftype-search-results.js]: Cache the searchTerms length. It's not a huge deal here, but it's a good practice.

File: js/page-specific/swiftype-search-results.js (hunk 1 above)
Comment (martypowell) [reply js/page-specific/swiftype-search-results.js]: done

File: js/page-specific/swiftype-search-results.js (hunk 3 above)
Comment (martypowell) [reply js/page-specific/swiftype-search-results.js]: done

File: js/page-specific/swiftype-search-results.js (hunk 2 above)
Comment (martypowell) [reply js/page-specific/swiftype-search-results.js]: The for loops excludes the + symbol, but I can change this.

File: js/page-specific/swiftype-search-results.js [hunk 4]
```diff
@@ -15,21 +15,15 @@ baltimoreCounty.pageSpecific.swiftypeSearchResults = (function swiftypeSearchRes
...
+		for (var i = 0, len = searchTerms.length; i < len; i += 1) {
 			var term = decodeURIComponent(searchTerms[i]);
-			term = term
-				.replace(/\?/g, '')
-				.replace(/#/g, ' ')
-				.replace(/&/g, 'and')
-				.replace(/\//g, ' ')
-				.replace(/\\/g, ' ');
+			term = term.replace(/[&?#\\/]/g, ' ')
+				.replace(/&/g, 'and').trim();
```
Comment (mxsnyder) [inline js/page-specific/swiftype-search-results.js]: The second replace will never succeed, since you're replacing "&" in the first replace.
