### PR TITLE
Template events fix

### LINKED ISSUE #70: Hamburger Menu Does not Work during releases
More information to follow.

### PR DESCRIPTION
**Pull request by martypowell**
Fixes #70 - Includes the hamburger event on the homepage

### CODE REVIEW

File: js/internal-template-events.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+(function ($) {
+  /*Submit url to rate form*/
+  $(document).on('submit', '#RateThisPageForm', function () {
```
Comment (mxsnyder) [inline js/internal-template-events.js]: While the style guide is somewhat inconsistent on this, I think event handlers should be extracted as named functions rather than using anonymous functions. For example:

// Bad
```JavaScript
$('p').on('click', function(e) { ... });
```
// Good
```JavaScript
var doSomething = function() { ... }

$('p').on('click', doSomething);
```

I'm only going to comment this in once, but it applies to everything. If you disagree, I'm open to discussion.

File: js/template-events.js [hunk 2]
```diff
@@ -1,32 +1,23 @@
-(function($, TextResizer) {
-	/*Prevent a search with no text*/
-	$(document).on('click', '.search-button', function (e) {
-        var val = $('.search-input').val();
+(function ($, TextResizer) {
+  /*Prevent a search with no text*/
+  $(document).on('click', '.search-button', function (e) {
```
Comment (mxsnyder) [inline js/template-events.js]: I know this is legacy, but for readability, consider changing:

```JavaScript
// Before
$(document).on('click', '.search-button', function (e) { ... })

// After (also assumes anonymous function was extracted)
$('.search-button').on('click', searchButtonClicked);
```

File: js/internal-template-events.js [hunk 3]
```diff
@@ -1,10 +1,11 @@
...
+  function ratePage() {
     document.getElementById('url').value = window.location.href;
 
     if ($('input#website').val().length) {
       return false;
     }
-  });
+  }
+  /*Submit url to rate form*/
+  $('#RateThisPageForm').on('submit', ratePage);
```
Comment (mxsnyder) [inline js/internal-template-events.js]: As discussed, the binding statements can be switched back to the $(document) way of doing things.
