### PR TITLE
Accordion menu fix

### LINKED ISSUE #105: 1.7 Release: Accordion Menu Carets Don't Rotate
You can see this in dev currently -- prod is not affected until tonight's release: http://www.baltimorecountymd.gov/Agencies/animalservices/index.html.

Red carets to the right of accordion menus don't rotate when expended. Related to the top-level highlighting change in this release? Not a showstopper in the least.

### PR DESCRIPTION
**Pull request by martypowell**
Resolves #105 

Rolled back to working code, and added fix for single links

### CODE REVIEW

File: js/accordion-menu.js [hunk 1]
```diff
@@ -1,26 +1,30 @@
...
+but that didn't work if the top-level category had no children
+gotcha
+tahnks
+i knew i could count on you
+Dan Fox (dan.ian.fox@gmail.com)
+i think the update to fix that also broke the arrows
+haha
+look here: https://wwww.baltimorecountymd.gov/Agencies/animalservices/jobs.html
+that page is an example
+*/
```
Comment (ascire) [inline js/accordion-menu.js]: I would at least clean this up a bit before merging.

Comment (martypowell) [reply js/accordion-menu.js]: @ascire done
